### ISSUE TITLE
Variables cannot be accessed properly after loading a session

### ISSUE THREAD

**Issue by jonasschneidercgg** [constructivegravity/construct#4]
If one generates a tensor and stores it in a variable, generates another tensor and
saves the session, i.e.

```
Arbitrary({a b c d e})
Simplify(%)
lambda = %
Arbitrary({a b c})
SaveSession("session.csd")
```

and loads the session another time and tries to use the variable, i.e.

```
LoadSession("session.csd")
Symmetrize(lambda, {a b})
```

one gets an error.

**Comment by jonasschneidercgg** [comment]
[2232Session.txt](https://github.com/constructivegravity/construct/files/371367/2232Session.txt)

**Comment by crazyphysicist** [comment]
Fixed, will be merged soon.
